# -*- coding: utf-8 -*-
"""Morning / Night Runs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJCxqw7X98I6a6zkV1MCGYpFZHEuiVHS

Run this code to collect YOLO detection data for chosen live streams for a chosen time frame. Swap out the live streams for your desired live streams, and adjust the code as necessary to align with your desired data collection. The results will be bounding box images as well as the saved data in CSV, both to be used later for analysis and pre-processing.
"""

!pip install ultralytics yt-dlp opencv-python pandas numpy matplotlib

import cv2
import pandas as pd
import time
from ultralytics import YOLO
import yt_dlp
import os
from datetime import datetime
import concurrent.futures
import threading
import numpy as np

# Define all your junction details
junctions = [
    {"url": "https://www.youtube.com/watch?v=Fbm5c19rg7I", "city": "Dublin", "junction_id": "junction1"},
    {"url": "https://www.youtube.com/watch?v=u4UZ4UvZXrg", "city": "Dublin", "junction_id": "junction2"},
    {"url": "https://www.youtube.com/watch?v=Z6_JOqkA1ik", "city": "Dublin", "junction_id": "junction3"},
    {"url": "https://www.youtube.com/watch?v=1phWWCgzXgM", "city": "Amsterdam", "junction_id": "junction1"},
    {"url": "https://www.youtube.com/watch?v=Gd9d4q6WvUY", "city": "Amsterdam", "junction_id": "junction2"},
    {"url": "https://www.youtube.com/watch?v=R5i7aeV8SB8", "city": "Amsterdam", "junction_id": "junction3"},
]

# Create a folder for today's date
today = datetime.now().strftime("%Y%m%d")
data_folder = f"traffic_data/{today}"
images_folder = f"traffic_images/{today}"
os.makedirs(data_folder, exist_ok=True)
os.makedirs(images_folder, exist_ok=True)

# Set which time period this is
time_period = "morning_rush"

# Create a print lock to avoid messy console output
print_lock = threading.Lock()

def process_junction(junction):
    """Process a single junction and save data to CSV"""
    try:
        with print_lock:
            print(f"Starting {junction['city']} - {junction['junction_id']}")

        # Create junction-specific images folder
        junction_img_folder = os.path.join(images_folder, f"{junction['city']}_{junction['junction_id']}")
        os.makedirs(junction_img_folder, exist_ok=True)

        # Get direct video URL
        ydl_opts = {'format': 'best[ext=mp4]', 'quiet': True}
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(junction['url'], download=False)
            video_url = info['url']

        # Initialize YOLO
        model = YOLO('yolov8n.pt')

        # Define colors for each class (BGR format for OpenCV)
        COLORS = {
            'person': (0, 255, 0),      # Green
            'bicycle': (255, 0, 0),     # Blue
            'car': (0, 0, 255),         # Red
            'motorcycle': (255, 255, 0), # Cyan
            'bus': (255, 0, 255),       # Magenta
            'truck': (0, 255, 255)      # Yellow
        }

        # Open video stream
        cap = cv2.VideoCapture(video_url)
        if not cap.isOpened():
            with print_lock:
                print(f"Error: Could not open video stream for {junction['city']} - {junction['junction_id']}")
            return

        # Prepare data collection
        traffic_data = []
        start_time = time.time()
        frame_count = 0

        # Process for 15 minutes
        while cap.isOpened() and (time.time() - start_time < 900):  # 900 seconds = 15 minutes
            ret, frame = cap.read()
            if not ret:
                break

            # Process every 30th frame
            if frame_count % 30 == 0:
                # Run YOLO detection
                results = model(frame)

                # Count objects
                counts = {'person': 0, 'bicycle': 0, 'car': 0, 'motorcycle': 0, 'bus': 0, 'truck': 0}

                # Create a copy of the frame for drawing bounding boxes if needed
                display_frame = None
                if frame_count % 1000 == 0:  # Save image every 1000 frames
                    display_frame = frame.copy()

                for r in results:
                    for box in r.boxes:
                        class_id = int(box.cls[0].item())
                        confidence = box.conf[0].item()

                        # Map class_id to name
                        class_name = None
                        if class_id == 0 and confidence > 0.5:
                            class_name = 'person'
                            counts['person'] += 1
                        elif class_id == 1 and confidence > 0.5:
                            class_name = 'bicycle'
                            counts['bicycle'] += 1
                        elif class_id == 2 and confidence > 0.5:
                            class_name = 'car'
                            counts['car'] += 1
                        elif class_id == 3 and confidence > 0.5:
                            class_name = 'motorcycle'
                            counts['motorcycle'] += 1
                        elif class_id == 5 and confidence > 0.5:
                            class_name = 'bus'
                            counts['bus'] += 1
                        elif class_id == 7 and confidence > 0.5:
                            class_name = 'truck'
                            counts['truck'] += 1

                        # If we're saving an image and a valid class was detected, draw bounding box
                        if display_frame is not None and class_name is not None:
                            x1, y1, x2, y2 = map(int, box.xyxy[0].tolist())
                            color = COLORS[class_name]
                            cv2.rectangle(display_frame, (x1, y1), (x2, y2), color, 2)

                            # Add label
                            label = f"{class_name} {confidence:.2f}"
                            cv2.putText(display_frame, label, (x1, y1-10),
                                      cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

                # Store data
                current_time = time.time() - start_time
                data_point = {
                    "timestamp": current_time,
                    "frame": frame_count,
                    **counts
                }
                traffic_data.append(data_point)

                # Save image with bounding boxes if it's time
                if display_frame is not None:
                    # Add text with stats at the top of the frame
                    vehicles = counts['car'] + counts['bus'] + counts['truck'] + counts['motorcycle']
                    stats_text = f"{junction['city']} - {junction['junction_id']} | Time: {current_time:.1f}s | Vehicles: {vehicles} | People: {counts['person']}"
                    cv2.putText(display_frame, stats_text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 0), 2)

                    # Save the image
                    img_filename = os.path.join(junction_img_folder, f"{time_period}_frame{frame_count}.jpg")
                    cv2.imwrite(img_filename, display_frame)
                    with print_lock:
                        print(f"Saved visualization image: {img_filename}")

                # Print status update (with lock to prevent mixed output)
                vehicles = counts['car'] + counts['bus'] + counts['truck'] + counts['motorcycle']
                with print_lock:
                    print(f"{junction['city']} - {junction['junction_id']} | Time: {current_time:.1f}s | Vehicles: {vehicles} | People: {counts['person']}")

            frame_count += 1

        # Release resources
        cap.release()

        # Save data to CSV
        if traffic_data:
            df = pd.DataFrame(traffic_data)

            # Add vehicles column
            df['vehicles'] = df['car'] + df['bus'] + df['truck'] + df['motorcycle']

            # Create filename
            filename = os.path.join(data_folder, f"{junction['city']}_{junction['junction_id']}_{time_period}.csv")

            # Save
            df.to_csv(filename, index=False)
            with print_lock:
                print(f"Saved data for {junction['city']} - {junction['junction_id']} to {filename}")

        with print_lock:
            print(f"Finished {junction['city']} - {junction['junction_id']}\n")

    except Exception as e:
        with print_lock:
            print(f"Error processing {junction['city']} - {junction['junction_id']}: {str(e)}")

# Process all junctions in parallel
print(f"Starting parallel processing of {len(junctions)} junctions")
print(f"Time period: {time_period}")
print(f"Data will be saved to: {data_folder}/")
print(f"Images will be saved to: {images_folder}/")
print("Processing will take approximately 15 minutes")
print("-" * 50)

# Use ThreadPoolExecutor to run all junctions in parallel
with concurrent.futures.ThreadPoolExecutor(max_workers=len(junctions)) as executor:
    # Submit all junction processing tasks
    futures = [executor.submit(process_junction, junction) for junction in junctions]

    # Wait for all to complete
    concurrent.futures.wait(futures)

print("All junctions processed!")
print(f"Data collected for time period: {time_period}")
print(f"Check the folder: {data_folder}/ for CSV files")
print(f"Check the folder: {images_folder}/ for visualization images")