# -*- coding: utf-8 -*-
"""Thesis - Data Analysis and Model Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KvOQ86FqpPUho3_ZOSEnGKR8EATXv8z

# Install Packages
"""

!pip install ultralytics opencv-python pandas numpy

"""# Re-run YOLO on troubled junction (if necessary)

"""

# Install required packages (run this cell first)
!pip install ultralytics

# Import libraries
import cv2
import numpy as np
import os
import time
import pandas as pd
from ultralytics import YOLO
from google.colab import files
import matplotlib.pyplot as plt

# Load the YOLOv8 model
!yolo task=detect mode=predict model=yolov8n.pt help=False  # This downloads the model

# Load the model for Python use
model = YOLO('yolov8n.pt')

# Create output folder for visualization
!mkdir -p processed_images

def process_single_image(img_path, output_file, time_period, day_type):
    """Process a single image and create a dataset row."""

    if not os.path.exists(img_path):
        print(f"File not found: {img_path}")
        return None

    # Create dataframe to store result
    results_df = pd.DataFrame(columns=[
        'timestamp', 'frame', 'person', 'bicycle', 'car',
        'motorcycle', 'bus', 'truck', 'vehicles',
        'time_period', 'day_type'
    ])

    # Generate timestamp (simulated)
    timestamp = time.time()

    # Load image
    img = cv2.imread(img_path)

    # Optional: Enhance image if necessary (uncomment if needed)
    # For night images, you might want to enhance brightness
    if time_period == "night":
        img = cv2.convertScaleAbs(img, alpha=1.5, beta=20)

    # Run YOLO detection with lower confidence for better detection
    results = model(img, conf=0.25)

    # Initialize counts
    counts = {
        'person': 0,
        'bicycle': 0,
        'car': 0,
        'motorcycle': 0,
        'bus': 0,
        'truck': 0
    }

    # Process detections
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # Get class name
            cls_id = int(box.cls.item())
            cls_name = model.names[cls_id]

            # Count objects of interest
            if cls_name in counts:
                counts[cls_name] += 1

    # Calculate vehicles (sum of all vehicle types)
    vehicle_count = counts['car'] + counts['motorcycle'] + counts['bus'] + counts['truck']

    # Create 10 rows of data with frame numbers (to match your example format)
    # This simulates having multiple frames from video
    for i in range(10):
        frame_num = i * 30  # 30 frames apart
        timestamp_offset = timestamp + (i * 3.0)  # 3 seconds apart

        new_row = {
            'timestamp': timestamp_offset,
            'frame': frame_num,
            'person': counts['person'],
            'bicycle': counts['bicycle'],
            'car': counts['car'],
            'motorcycle': counts['motorcycle'],
            'bus': counts['bus'],
            'truck': counts['truck'],
            'vehicles': vehicle_count,
            'time_period': time_period,
            'day_type': day_type
        }
        results_df = pd.concat([results_df, pd.DataFrame([new_row])], ignore_index=True)

    # Save annotated image for verification
    img_annotated = results[0].plot()
    output_image = f"processed_images/{day_type}_{time_period}.jpg"
    cv2.imwrite(output_image, img_annotated)

    print(f"Processed {img_path}: {counts}")

    # Save to CSV
    results_df.to_csv(output_file, index=False)
    print(f"Results saved to {output_file}")

    # Download the CSV file
    files.download(output_file)

    return results_df, counts

# Define the 4 scenarios
scenarios = [
    {"filename": "/content/wed morn.jpg", "output": "junction_weekday_morning.csv", "time_period": "morning", "day_type": "weekday"},
    {"filename": "/content/wed night .jpg", "output": "junction_weekday_night.csv", "time_period": "night", "day_type": "weekday"},
    {"filename": "/content/sat morn.jpg", "output": "junction_weekend_morning.csv", "time_period": "morning", "day_type": "weekend"},
    {"filename": "/content/sat night.jpeg", "output": "junction_weekend_night.csv", "time_period": "night", "day_type": "weekend"}
]

# Process each image and collect results
all_results = []
count_summary = {}

for scenario in scenarios:
    print(f"\nProcessing {scenario['time_period']} {scenario['day_type']} image...")

    # Process the image
    result, counts = process_single_image(
        scenario["filename"],
        scenario["output"],
        scenario["time_period"],
        scenario["day_type"]
    )

    if result is not None:
        all_results.append(result)
        count_summary[f"{scenario['day_type']}_{scenario['time_period']}"] = counts

# Combine all results
if all_results:
    combined_results = pd.concat(all_results)
    combined_results.to_csv("junction_all_combined.csv", index=False)
    files.download("junction_all_combined.csv")

    # Create visualization comparing all scenarios
    plt.figure(figsize=(12, 8))

    # Bar chart of vehicle counts
    categories = list(count_summary.keys())
    cars = [count_summary[cat]['car'] for cat in categories]
    buses = [count_summary[cat]['bus'] for cat in categories]
    bicycles = [count_summary[cat]['bicycle'] for cat in categories]
    people = [count_summary[cat]['person'] for cat in categories]

    x = np.arange(len(categories))
    width = 0.2

    plt.bar(x - width*1.5, cars, width, label='Cars')
    plt.bar(x - width/2, buses, width, label='Buses')
    plt.bar(x + width/2, bicycles, width, label='Bicycles')
    plt.bar(x + width*1.5, people, width, label='People')

    plt.xlabel('Scenario')
    plt.ylabel('Count')
    plt.title('Object Counts by Scenario')
    plt.xticks(x, categories)
    plt.legend()
    plt.grid(True, axis='y')

    plt.tight_layout()
    plt.show()

"""# Merging Data Per Junction

"""

from google.colab import drive
drive.mount('/content/drive', force_remount = True)

from google.colab import drive
import os
import glob
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive', force_remount=True)

# Base path to start searching
base_path = "/content/drive/MyDrive/"

# Function to find all CSV files within a directory and its subdirectories
def find_all_csv_files(start_path):
    all_csvs = []
    for root, dirs, files in os.walk(start_path):
        for file in files:
            if file.endswith('.csv'):
                all_csvs.append(os.path.join(root, file))
    return all_csvs

# Find all CSV files in your Drive
print("Searching for CSV files in your Google Drive...")
csv_files = find_all_csv_files(base_path)

# Show how many files were found
print(f"Found {len(csv_files)} CSV files in total")

# Show more files and their paths
if csv_files:
    # Ask how many files to display
    try:
        num_to_show = int(input("How many CSV files would you like to see? (Enter a number): "))
    except:
        num_to_show = 30  # Default if input is not a valid number

    print(f"\nShowing {min(num_to_show, len(csv_files))} CSV files and their locations:")
    for file in csv_files[:num_to_show]:
        print(f" - {file}")

    # Ask if these are the right files
    answer = input("\nAre these the CSV files you're looking for? (yes/no): ")

    if answer.lower() == 'yes':
        print("\nGreat! Using all found CSV files for your analysis.")
        # Save the paths for future use
        csv_paths = csv_files
    else:
        print("\nLet's try to narrow down the search.")
        folder_hint = input("Enter part of the folder name where your CSV files are stored: ")

        # Filter files by the folder hint
        filtered_files = [f for f in csv_files if folder_hint in f]
        print(f"\nFound {len(filtered_files)} CSV files containing '{folder_hint}' in their path")

        # Show a subset of the filtered files
        num_to_show = min(len(filtered_files), 30)
        if num_to_show > 0:
            print(f"Showing first {num_to_show} filtered files:")
            for file in filtered_files[:num_to_show]:
                print(f" - {file}")

            # Save the filtered paths
            csv_paths = filtered_files
        else:
            print(f"No files found containing '{folder_hint}' in their path.")
else:
    print("No CSV files found in your Google Drive.")

# Print the total number of files that will be used
if 'csv_paths' in locals() and csv_paths:
    print(f"\nTotal number of CSV files to be used: {len(csv_paths)}")

import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

# Improved function to extract metadata from filepaths that works with your naming convention
def extract_metadata(filepath):
    # Look at the full path, not just the filename
    full_path = filepath.lower()
    base_name = os.path.basename(filepath).lower().replace('.csv', '')

    # For Amsterdam junction2's special weekday/weekend files
    if 'amsterdam2_weekday' in full_path or 'amsterdam2_weekend' in full_path:
        city = 'Amsterdam'
        junction_number = 2
    else:
        # More flexible pattern matching for various filename formats
        amsterdam_match = re.search(r'amsterdam[_\s]*(junction)?[_\s]*(\d)', full_path)
        dublin_match = re.search(r'dublin[_\s]*(junction)?[_\s]*(\d)', full_path)

        if amsterdam_match:
            city = 'Amsterdam'
            # The junction number might be in group 1 or 2 depending on the pattern
            junction_number = int(amsterdam_match.group(2) if amsterdam_match.group(2) else amsterdam_match.group(1))
        elif dublin_match:
            city = 'Dublin'
            # The junction number might be in group 1 or 2 depending on the pattern
            junction_number = int(dublin_match.group(2) if dublin_match.group(2) else dublin_match.group(1))
        else:
            city = None
            junction_number = None

    # Create a junction ID
    if city and junction_number is not None:
        junction_id = f"{city}{junction_number}"
    else:
        junction_id = None

    # Time period identification from filename or path
    if 'morning' in full_path:
        time_period = 'morning'
    elif 'night' in full_path or 'evening' in full_path:
        time_period = 'night'
    else:
        time_period = None

    # Day identification from filename or path - check for both specific days and weekday/weekend
    day_options = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'weekday', 'weekend']
    day = next((d for d in day_options if d in full_path), None)

    return {
        'city': city,
        'junction_number': junction_number,
        'junction_id': junction_id,
        'day': day,
        'time_period': time_period,
        'filepath': full_path  # For debugging
    }

# Print examples of extracted metadata to verify it's working correctly
print("\nMetadata extraction examples:")
for file_path in csv_paths[:10]:  # Check first 10 files
    metadata = extract_metadata(file_path)
    print(f"File: {os.path.basename(file_path)}")
    print(f"Extracted metadata: {metadata}")
    print("---")

# Function to load junction data
def load_junction_data(file_paths, problem_junction="Amsterdam2"):
    # Dictionary to store dataframes by junction
    junction_data = {}

    # Track the detected junctions
    detected_junctions = set()

    # First pass: identify all junctions
    for file_path in file_paths:
        metadata = extract_metadata(file_path)
        if metadata['junction_id']:
            detected_junctions.add(metadata['junction_id'])

    print(f"Detected junctions: {sorted(list(detected_junctions))}")
    print(f"Using '{problem_junction}' as the problematic junction")

    # Second pass: load the data
    for file_path in file_paths:
        metadata = extract_metadata(file_path)

        # Skip if we couldn't identify the junction
        if not metadata['junction_id']:
            print(f"Skipping {os.path.basename(file_path)} - could not identify junction")
            continue

        # Special handling for problematic junction
        if metadata['junction_id'] == problem_junction:
            # For the problem junction, only use weekday/weekend data
            if metadata['day'] in ['weekday', 'weekend']:
                pass  # Process this file
            else:
                print(f"Skipping non-weekday/weekend data for problem junction: {os.path.basename(file_path)}")
                continue

        # Read the file
        try:
            df = pd.read_csv(file_path)

            # Add metadata columns
            df['city'] = metadata['city']
            df['junction_number'] = metadata['junction_number']
            df['junction_id'] = metadata['junction_id']
            df['day'] = metadata['day']
            df['time_period'] = metadata['time_period']

            # Initialize or append to the junction's data
            if metadata['junction_id'] not in junction_data:
                junction_data[metadata['junction_id']] = df
            else:
                junction_data[metadata['junction_id']] = pd.concat([junction_data[metadata['junction_id']], df])

            print(f"Added {len(df)} rows from {os.path.basename(file_path)} for {metadata['junction_id']}")
        except Exception as e:
            print(f"Error reading {os.path.basename(file_path)}: {str(e)}")

    return junction_data

# Function to analyze junctions
def analyze_junctions(junction_data):
    # Create a dataframe for junction profiles
    profiles = []

    for junction_id, data in junction_data.items():
        print(f"Analyzing junction: {junction_id}")

        try:
            # Calculate basic statistics
            morning_stats = data[data['time_period'] == 'morning'].agg({
                'person': 'mean',
                'bicycle': 'mean',
                'car': 'mean',
                'motorcycle': 'mean',
                'bus': 'mean',
                'truck': 'mean',
                'vehicles': 'mean'
            })

            night_stats = data[data['time_period'] == 'night'].agg({
                'person': 'mean',
                'bicycle': 'mean',
                'car': 'mean',
                'motorcycle': 'mean',
                'bus': 'mean',
                'truck': 'mean',
                'vehicles': 'mean'
            })

            weekday_stats = data[data['day'].isin(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'weekday'])].agg({
                'person': 'mean',
                'bicycle': 'mean',
                'car': 'mean',
                'motorcycle': 'mean',
                'bus': 'mean',
                'truck': 'mean',
                'vehicles': 'mean'
            })

            weekend_stats = data[data['day'].isin(['saturday', 'sunday', 'weekend'])].agg({
                'person': 'mean',
                'bicycle': 'mean',
                'car': 'mean',
                'motorcycle': 'mean',
                'bus': 'mean',
                'truck': 'mean',
                'vehicles': 'mean'
            })

            # Get city and junction number
            city = data['city'].iloc[0]
            junction_number = data['junction_number'].iloc[0]

            # Calculate key metrics (with 0.1 added to avoid division by zero)
            total_vehicles = data['vehicles'].mean()
            person_to_vehicle = data['person'].sum() / (data['vehicles'].sum() + 0.1)
            car_percentage = (data['car'].sum() / (data['vehicles'].sum() + 0.1)) * 100
            bicycle_percentage = (data['bicycle'].sum() / (data['vehicles'].sum() + 0.1)) * 100

            # Calculate ratios safely (handling empty data)
            if not morning_stats.empty and not night_stats.empty and night_stats['vehicles'] > 0:
                morning_to_night_ratio = morning_stats['vehicles'] / night_stats['vehicles']
            else:
                morning_to_night_ratio = np.nan

            if not weekday_stats.empty and not weekend_stats.empty and weekend_stats['vehicles'] > 0:
                weekday_to_weekend_ratio = weekday_stats['vehicles'] / weekend_stats['vehicles']
            else:
                weekday_to_weekend_ratio = np.nan

            # Create profile
            profile = {
                'junction_id': junction_id,
                'city': city,
                'junction_number': junction_number,
                'avg_vehicles': total_vehicles,
                'person_to_vehicle_ratio': person_to_vehicle,
                'car_percentage': car_percentage,
                'bicycle_percentage': bicycle_percentage,
                'morning_traffic': morning_stats['vehicles'] if not morning_stats.empty else np.nan,
                'night_traffic': night_stats['vehicles'] if not night_stats.empty else np.nan,
                'morning_to_night_ratio': morning_to_night_ratio,
                'weekday_traffic': weekday_stats['vehicles'] if not weekday_stats.empty else np.nan,
                'weekend_traffic': weekend_stats['vehicles'] if not weekend_stats.empty else np.nan,
                'weekday_to_weekend_ratio': weekday_to_weekend_ratio,
                'morning_people': morning_stats['person'] if not morning_stats.empty else np.nan,
                'night_people': night_stats['person'] if not night_stats.empty else np.nan,
                'morning_cars': morning_stats['car'] if not morning_stats.empty else np.nan,
                'night_cars': night_stats['car'] if not night_stats.empty else np.nan,
                'morning_bicycles': morning_stats['bicycle'] if not morning_stats.empty else np.nan,
                'night_bicycles': night_stats['bicycle'] if not night_stats.empty else np.nan
            }

            profiles.append(profile)

        except Exception as e:
            print(f"Error analyzing junction {junction_id}: {str(e)}")

    # Convert to dataframe
    junction_profiles = pd.DataFrame(profiles)

    return junction_profiles

# Function to create visualizations
def visualize_junction_characteristics(junction_profiles, junction_data):
    # Create output directory for plots
    output_dir = 'junction_plots'
    os.makedirs(output_dir, exist_ok=True)

    # Sort junction profiles for consistent ordering in visualizations
    # This will ensure Amsterdam2 appears between Amsterdam1 and Amsterdam3
    junction_profiles = junction_profiles.sort_values(by=['city', 'junction_number']).reset_index(drop=True)

    # Get the sorted junction_ids to use as order in plots
    sorted_junction_ids = junction_profiles['junction_id'].tolist()

    # Set up the plot style
    sns.set(style="whitegrid")
    plt.rcParams['figure.figsize'] = (12, 8)
    plt.rcParams['font.size'] = 12

    print("Creating visualizations...")

    # 1. Traffic volume by city and junction
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(x='junction_id', y='avg_vehicles', hue='city', data=junction_profiles, order=sorted_junction_ids)
    ax.set_title('Average Traffic Volume by Junction', fontsize=14)
    ax.set_ylabel('Average Vehicle Count', fontsize=12)
    ax.set_xlabel('Junction ID', fontsize=12)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/traffic_volume_by_junction.png', dpi=300)
    plt.show()
    print("Created: Traffic volume visualization")

    # 2. Morning vs. Night comparison
    plt.figure(figsize=(14, 7))

    # Create a dataframe for plotting
    time_comparison = pd.melt(
        junction_profiles,
        id_vars=['junction_id', 'city'],
        value_vars=['morning_traffic', 'night_traffic'],
        var_name='Time Period',
        value_name='Traffic'
    )

    # Replace the variable names for better readability
    time_comparison['Time Period'] = time_comparison['Time Period'].replace({
        'morning_traffic': 'Morning',
        'night_traffic': 'Night'
    })

    # Create the plot
    ax = sns.barplot(x='junction_id', y='Traffic', hue='Time Period', data=time_comparison, order=sorted_junction_ids)
    ax.set_title('Morning vs. Night Traffic by Junction', fontsize=14)
    ax.set_ylabel('Average Vehicle Count', fontsize=12)
    ax.set_xlabel('Junction ID', fontsize=12)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/morning_vs_night_traffic.png', dpi=300)
    plt.show()
    print("Created: Morning vs. Night traffic visualization")

    # 3. Weekday vs. Weekend comparison
    plt.figure(figsize=(14, 7))

    # Create a dataframe for plotting
    day_comparison = pd.melt(
        junction_profiles,
        id_vars=['junction_id', 'city'],
        value_vars=['weekday_traffic', 'weekend_traffic'],
        var_name='Day Type',
        value_name='Traffic'
    )

    # Replace the variable names for better readability
    day_comparison['Day Type'] = day_comparison['Day Type'].replace({
        'weekday_traffic': 'Weekday',
        'weekend_traffic': 'Weekend'
    })

    # Create the plot
    ax = sns.barplot(x='junction_id', y='Traffic', hue='Day Type', data=day_comparison, order=sorted_junction_ids)
    ax.set_title('Weekday vs. Weekend Traffic by Junction', fontsize=14)
    ax.set_ylabel('Average Vehicle Count', fontsize=12)
    ax.set_xlabel('Junction ID', fontsize=12)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/weekday_vs_weekend_traffic.png', dpi=300)
    plt.show()
    print("Created: Weekday vs. Weekend traffic visualization")

    # 4. Transportation modal split
    # Calculate percentages for different transport modes
    transport_data = []

    for _, row in junction_profiles.iterrows():
        transport_data.append({
            'junction_id': row['junction_id'],
            'city': row['city'],
            'transport_mode': 'Cars',
            'percentage': row['car_percentage']
        })
        transport_data.append({
            'junction_id': row['junction_id'],
            'city': row['city'],
            'transport_mode': 'Bicycles',
            'percentage': row['bicycle_percentage']
        })
        transport_data.append({
            'junction_id': row['junction_id'],
            'city': row['city'],
            'transport_mode': 'Other Vehicles',
            'percentage': 100 - (row['car_percentage'] + row['bicycle_percentage'])
        })

    transport_df = pd.DataFrame(transport_data)

    # Create stacked bar chart
    plt.figure(figsize=(15, 8))

    # Get unique transport modes and use sorted junction IDs
    modes = transport_df['transport_mode'].unique()
    junctions = sorted_junction_ids

    # For each junction, create a stacked bar
    bottom = np.zeros(len(junctions))

    for mode in modes:
        heights = []
        for j in junctions:
            value = transport_df[(transport_df['junction_id'] == j) &
                                (transport_df['transport_mode'] == mode)]['percentage'].values[0]
            heights.append(value)

        plt.bar(junctions, heights, bottom=bottom, label=mode)
        bottom += heights

    plt.title('Transport Mode Distribution by Junction', fontsize=14)
    plt.ylabel('Percentage (%)', fontsize=12)
    plt.xlabel('Junction ID', fontsize=12)
    plt.xticks(rotation=45)
    plt.legend(title='Transport Mode')
    plt.tight_layout()
    plt.savefig(f'{output_dir}/transport_mode_distribution.png', dpi=300)
    plt.show()
    print("Created: Transport mode distribution visualization")

    # 5. Person to vehicle ratio
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(x='junction_id', y='person_to_vehicle_ratio', hue='city', data=junction_profiles, order=sorted_junction_ids)
    ax.set_title('Person to Vehicle Ratio by Junction', fontsize=14)
    ax.set_ylabel('Ratio (persons per vehicle)', fontsize=12)
    ax.set_xlabel('Junction ID', fontsize=12)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/person_to_vehicle_ratio.png', dpi=300)
    plt.show()
    print("Created: Person to vehicle ratio visualization")

    # 6. Weekly patterns (for junctions with daily data)
    print("Creating weekly pattern visualizations for junctions with daily data...")
    for junction_id, data in junction_data.items():
        # Only process if we have daily data (not just weekday/weekend)
        if any(day in data['day'].unique() for day in ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']):
            # Group by day and calculate mean values
            daily_stats = data.groupby('day').agg({
                'vehicles': 'mean',
                'person': 'mean',
                'car': 'mean',
                'bicycle': 'mean'
            }).reset_index()

            # Define day order for sorting
            day_order = {'monday': 0, 'tuesday': 1, 'wednesday': 2, 'thursday': 3,
                         'friday': 4, 'saturday': 5, 'sunday': 6, 'weekday': 7, 'weekend': 8}
            daily_stats['day_order'] = daily_stats['day'].map(day_order)
            daily_stats = daily_stats.sort_values('day_order')

            # Create the plot
            plt.figure(figsize=(14, 8))

            # Plot vehicles
            plt.subplot(2, 1, 1)
            plt.plot(daily_stats['day'], daily_stats['vehicles'], marker='o', linewidth=2, label='Vehicles')
            plt.plot(daily_stats['day'], daily_stats['car'], marker='s', linewidth=2, label='Cars')
            plt.plot(daily_stats['day'], daily_stats['bicycle'], marker='^', linewidth=2, label='Bicycles')
            plt.title(f'Weekly Vehicle Patterns for {junction_id}', fontsize=14)
            plt.ylabel('Average Count', fontsize=12)
            plt.xticks(rotation=45)
            plt.legend()
            plt.grid(True, alpha=0.3)

            # Plot people
            plt.subplot(2, 1, 2)
            plt.plot(daily_stats['day'], daily_stats['person'], marker='o', color='green', linewidth=2)
            plt.title(f'Weekly Pedestrian Patterns for {junction_id}', fontsize=14)
            plt.ylabel('Average Count', fontsize=12)
            plt.xticks(rotation=45)
            plt.grid(True, alpha=0.3)

            plt.tight_layout()
            plt.savefig(f'{output_dir}/weekly_patterns_{junction_id}.png', dpi=300)
            plt.show()
            print(f"  Created: Weekly patterns for {junction_id}")

    # 7. Junction Characteristics Heatmap
    plt.figure(figsize=(14, 10))

    # Select key metrics for the heatmap and use ordered junction IDs as index
    heatmap_data = junction_profiles.set_index('junction_id').loc[sorted_junction_ids,
                                  ['avg_vehicles', 'car_percentage', 'bicycle_percentage',
                                   'person_to_vehicle_ratio', 'morning_to_night_ratio',
                                   'weekday_to_weekend_ratio']]

    # Create a normalized version for the heatmap
    heatmap_normalized = (heatmap_data - heatmap_data.mean()) / heatmap_data.std()

    # Create the heatmap
    plt.figure(figsize=(14, 8))
    ax = sns.heatmap(heatmap_normalized, annot=heatmap_data.round(2), fmt='.2f',
                cmap='YlGnBu', linewidths=0.5, cbar_kws={'label': 'Z-score (standardized)'})
    ax.set_title('Junction Characteristics Comparison', fontsize=16)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/junction_characteristics_heatmap.png', dpi=300)
    plt.show()
    print("Created: Junction characteristics heatmap")

    # 8. City-based comparison - FIXED VERSION
    try:
        # Group by city correctly
        city_comparison = junction_profiles.groupby('city', as_index=False).agg({
            'avg_vehicles': 'mean',
            'car_percentage': 'mean',
            'bicycle_percentage': 'mean',
            'morning_to_night_ratio': 'mean',
            'weekday_to_weekend_ratio': 'mean'
        })

        # Create subplots
        fig, axes = plt.subplots(1, 3, figsize=(18, 6))

        # Traffic volume
        axes[0].bar(city_comparison['city'], city_comparison['avg_vehicles'], color=['skyblue', 'lightgreen'])
        axes[0].set_title('Average Traffic Volume')
        axes[0].set_ylabel('Vehicle Count')

        # Transport mode
        axes[1].bar(city_comparison['city'], city_comparison['car_percentage'], label='Cars', color='skyblue')
        axes[1].bar(city_comparison['city'], city_comparison['bicycle_percentage'],
                    bottom=city_comparison['car_percentage'], label='Bicycles', color='lightgreen')
        other_percentage = 100 - city_comparison['car_percentage'] - city_comparison['bicycle_percentage']
        axes[1].bar(city_comparison['city'], other_percentage,
                    bottom=city_comparison['car_percentage'] + city_comparison['bicycle_percentage'],
                    label='Other', color='lightcoral')
        axes[1].set_title('Transport Mode Distribution')
        axes[1].set_ylabel('Percentage (%)')
        axes[1].legend()

        # Temporal patterns - only if we have at least 2 cities
        if len(city_comparison) >= 2:
            axes[2].bar([0, 1], [city_comparison.iloc[0]['morning_to_night_ratio'],
                              city_comparison.iloc[0]['weekday_to_weekend_ratio']],
                      label=city_comparison.iloc[0]['city'], color='skyblue')
            axes[2].bar([3, 4], [city_comparison.iloc[1]['morning_to_night_ratio'],
                              city_comparison.iloc[1]['weekday_to_weekend_ratio']],
                      label=city_comparison.iloc[1]['city'], color='lightgreen')
            axes[2].set_title('Temporal Patterns')
            axes[2].set_ylabel('Ratio')
            axes[2].set_xticks([0.5, 3.5])
            axes[2].set_xticklabels(['Morning/Night', 'Weekday/Weekend'])
            axes[2].axhline(y=1, color='r', linestyle='--')  # Reference line for equal values
            axes[2].legend()

        plt.tight_layout()
        plt.savefig(f'{output_dir}/city_comparison.png', dpi=300)
        plt.show()
        print("Created: City comparison visualization")
    except Exception as e:
        print(f"Could not create city comparison visualization: {str(e)}")

    print(f"All visualizations saved to {output_dir} directory")
    return junction_profiles

# Load, analyze, and visualize the junction data using the paths we already found
print("\nLoading and processing junction data...")
junction_data = load_junction_data(csv_paths)

# Create junction profiles
print("\nCreating junction profiles...")
junction_profiles = analyze_junctions(junction_data)

# Create visualizations
print("\nCreating visualizations...")
visualize_junction_characteristics(junction_profiles, junction_data)

# Save the profiles
junction_profiles.to_csv('junction_profiles.csv', index=False)
print("\nJunction profiles saved to 'junction_profiles.csv'")

# Print summary of junction characteristics
print("\nJunction Characteristics Summary:")
summary = junction_profiles[['junction_id', 'city', 'avg_vehicles',
                           'car_percentage', 'bicycle_percentage',
                           'morning_to_night_ratio', 'weekday_to_weekend_ratio']]
print(summary.round(2))

"""# Feature selection

"""

# Select features for classification
features = junction_profiles[['avg_vehicles', 'car_percentage', 'bicycle_percentage',
                            'person_to_vehicle_ratio', 'morning_to_night_ratio',
                            'weekday_to_weekend_ratio']]

# Normalize/standardize the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

# Step 1: Evaluate different numbers of clusters using silhouette scores
silhouette_scores = []
k_range = range(2, min(6, len(features_scaled) + 1))  # Try 2–5 clusters

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(features_scaled)
    silhouette_scores.append(silhouette_score(features_scaled, cluster_labels))

# Step 2: Plot silhouette scores for visual inspection
plt.figure(figsize=(10, 6))
plt.plot(k_range, silhouette_scores, 'o-')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score vs. Number of Clusters')
plt.grid(True)
plt.show()

# Step 3: Print silhouette scores (optional for your report)
for k, score in zip(k_range, silhouette_scores):
    print(f"Silhouette score for k={k}: {score:.4f}")

# Step 4: Choose number of clusters
# Option 1: Use silhouette-based optimal k
optimal_k = k_range[silhouette_scores.index(max(silhouette_scores))]

# Option 2: Manually override based on Elbow Method
optimal_k = 3
print(f"Selected number of clusters: {optimal_k}")

# Step 5: Apply K-Means with the chosen number of clusters
kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
junction_profiles['cluster'] = kmeans.fit_predict(features_scaled)

# Step 6: Define descriptive cluster names based on your analysis
cluster_names = {
    0: "High-volume Urban Traffic Junction",
    1: "Mixed-use Active Transportation Hub",
    2: "Low-density Residential Junction"
}

# Step 7: Assign human-readable junction types
junction_profiles['junction_type'] = junction_profiles['cluster'].map(
    lambda x: cluster_names.get(x, f"Cluster {x}")
)

# Step 8: View clustered results
print(junction_profiles[['junction_id', 'city', 'junction_type']])

"""# Clustering

"""

# 1. Feature Selection and Preparation
# Select features for classification
features = junction_profiles[['avg_vehicles', 'car_percentage', 'bicycle_percentage',
                            'person_to_vehicle_ratio', 'morning_to_night_ratio',
                            'weekday_to_weekend_ratio']]

# Normalize/standardize the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

# 2. Clustering to Find Natural Junction Types
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import numpy as np

# Determine optimal number of clusters
silhouette_scores = []
k_range = range(3, min(6, len(features_scaled) + 1))

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(features_scaled)
    silhouette_scores.append(silhouette_score(features_scaled, cluster_labels))

# Plot silhouette scores
plt.figure(figsize=(10, 6))
plt.plot(k_range, silhouette_scores, 'o-')
plt.xlabel('Number of clusters')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score for Different Numbers of Clusters')
plt.grid(True)
plt.show()

# Apply K-means with optimal k (based on highest silhouette score)
optimal_k = k_range[silhouette_scores.index(max(silhouette_scores))]
print(f"Optimal number of clusters: {optimal_k}")

kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
junction_profiles['cluster'] = kmeans.fit_predict(features_scaled)

# Add descriptive cluster names
cluster_names = {
    0: "High-volume Urban Junction",
    1: "Mixed-use with High Pedestrian Activity",
    2: "Low-density Residential Junction"
    # Add more names based on your actual cluster characteristics
}

# Map cluster numbers to names (adjust the dictionary based on your results)
junction_profiles['junction_type'] = junction_profiles['cluster'].map(
    lambda x: cluster_names.get(x, f"Cluster {x}")
)

# View the results
print(junction_profiles[['junction_id', 'city', 'junction_type']])

# 3. Analyze Cluster Characteristics (FIXED VERSION)
# Calculate mean values for each feature by cluster with explicit column specification
cluster_profiles = junction_profiles.groupby('cluster', as_index=False).agg({
    'avg_vehicles': 'mean',
    'car_percentage': 'mean',
    'bicycle_percentage': 'mean',
    'person_to_vehicle_ratio': 'mean',
    'morning_to_night_ratio': 'mean',
    'weekday_to_weekend_ratio': 'mean'
})

# Set cluster as index after aggregation
cluster_profiles = cluster_profiles.set_index('cluster')

print("\nCluster characteristics:")
print(cluster_profiles)

# Visualize cluster characteristics
import seaborn as sns
from math import pi

# Function to create a radar chart
def radar_chart(df, cluster_names):
    # Number of variables
    categories = list(df.columns)
    N = len(categories)

    # Create a figure
    fig = plt.figure(figsize=(12, 8))

    # Create angles for each variable
    angles = [n / float(N) * 2 * pi for n in range(N)]
    angles += angles[:1]  # Close the loop

    # Create the plot
    ax = plt.subplot(111, polar=True)

    # Draw one axis per variable and add labels
    plt.xticks(angles[:-1], categories, size=12)

    # Draw ylabels
    ax.set_rlabel_position(0)
    plt.yticks([0.25, 0.5, 0.75], ["0.25", "0.5", "0.75"], color="grey", size=10)
    plt.ylim(0, 1)

    # Plot each cluster
    for i, cluster in enumerate(df.index):
        values = df.loc[cluster].values.tolist()
        values += values[:1]  # Close the loop
        ax.plot(angles, values, linewidth=2, linestyle='solid', label=cluster_names.get(cluster, f"Cluster {cluster}"))
        ax.fill(angles, values, alpha=0.1)

    # Add legend
    plt.legend(loc='upper right', bbox_to_anchor=(0.1, 0.1))
    plt.title("Cluster Characteristics", size=20, y=1.1)

    return fig

# Normalize data for radar chart
radar_data = cluster_profiles[['avg_vehicles', 'car_percentage', 'bicycle_percentage',
                              'person_to_vehicle_ratio', 'morning_to_night_ratio',
                              'weekday_to_weekend_ratio']]
radar_data = (radar_data - radar_data.min()) / (radar_data.max() - radar_data.min())

# Create radar chart
radar_chart(radar_data, cluster_names)
plt.tight_layout()
plt.savefig('cluster_radar_chart.png', dpi=300)
plt.show()

# 4. Visualize the Clusters
# PCA to visualize clusters in 2D
from sklearn.decomposition import PCA

# Apply PCA for visualization
pca = PCA(n_components=2)
principal_components = pca.fit_transform(features_scaled)

# Create a dataframe with the principal components
pca_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])
pca_df['junction_id'] = junction_profiles['junction_id']
pca_df['cluster'] = junction_profiles['cluster']
pca_df['junction_type'] = junction_profiles['junction_type']
pca_df['city'] = junction_profiles['city']

# Plot PCA results
plt.figure(figsize=(12, 8))
scatter = plt.scatter(pca_df['PC1'], pca_df['PC2'],
                     c=pca_df['cluster'], cmap='viridis',
                     s=100, alpha=0.8)

# Add junction labels
for i, row in pca_df.iterrows():
    plt.annotate(row['junction_id'],
                 (row['PC1'] + 0.1, row['PC2'] + 0.1),
                 fontsize=12)

# Add a legend
legend1 = plt.legend(*scatter.legend_elements(),
                    title="Clusters")
plt.gca().add_artist(legend1)

# Customize the plot
plt.title('Junction Clusters based on PCA', fontsize=16)
plt.xlabel('Principal Component 1', fontsize=14)
plt.ylabel('Principal Component 2', fontsize=14)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('junction_clusters_pca.png', dpi=300)
plt.show()

# Calculate feature importance for PC1 and PC2
feature_names = ['Avg. Vehicles', 'Car %', 'Bicycle %', 'Person/Vehicle Ratio',
                'Morning/Night Ratio', 'Weekday/Weekend Ratio']

# Get component loadings
loadings = pd.DataFrame(
    pca.components_.T,
    columns=['PC1', 'PC2'],
    index=feature_names
)

# Plot feature loadings
plt.figure(figsize=(10, 6))
loadings.plot(kind='bar')
plt.title('Feature Contributions to Principal Components', fontsize=14)
plt.ylabel('Contribution', fontsize=12)
plt.xlabel('Features', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('pca_feature_contributions.png', dpi=300)
plt.show()

# 5. Create a Junction Classification Model
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Prepare data for classification
X = features_scaled
y = junction_profiles['cluster']

# Since we have very few junctions, we'll use all data for training
# If you had more junctions, you could use train_test_split
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X, y)

# Feature importance
importances = clf.feature_importances_
feature_importance = pd.DataFrame({'feature': features.columns, 'importance': importances})
feature_importance = feature_importance.sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='importance', y='feature', data=feature_importance)
plt.title('Feature Importance for Junction Classification', fontsize=14)
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=300)
plt.show()

# 6. Function to Classify New Junctions
def classify_new_junction(new_features, model, scaler, cluster_names):
    """
    Classify a new junction based on its features

    Args:
        new_features (dict): Dictionary with junction features
        model: Trained classification model
        scaler: Fitted scaler
        cluster_names (dict): Mapping from cluster IDs to names

    Returns:
        dict: Classification results
    """
    # Convert input to DataFrame
    input_df = pd.DataFrame([new_features])

    # Scale features
    input_scaled = scaler.transform(input_df)

    # Predict cluster
    cluster = model.predict(input_scaled)[0]

    # Get probabilities for each cluster
    probs = model.predict_proba(input_scaled)[0]

    # Get junction type
    junction_type = cluster_names.get(cluster, f"Cluster {cluster}")

    # Find similar junctions (based on Euclidean distance)
    distances = []
    for i, row in enumerate(features_scaled):
        dist = np.linalg.norm(input_scaled - row.reshape(1, -1))
        distances.append((junction_profiles.iloc[i]['junction_id'], dist))

    # Sort by distance (most similar first)
    similar_junctions = sorted(distances, key=lambda x: x[1])[:2]

    return {
        'cluster': int(cluster),
        'junction_type': junction_type,
        'confidence': float(probs[cluster]),
        'similar_junctions': similar_junctions
    }

# Example new junction
new_junction = {
    'avg_vehicles': 50,
    'car_percentage': 70,
    'bicycle_percentage': 20,
    'person_to_vehicle_ratio': 1.2,
    'morning_to_night_ratio': 1.5,
    'weekday_to_weekend_ratio': 1.3
}

# Classify the new junction
result = classify_new_junction(new_junction, clf, scaler, cluster_names)
print("\nNew junction classification:")
print(f"Cluster: {result['cluster']}")
print(f"Junction Type: {result['junction_type']}")
print(f"Confidence: {result['confidence']:.2f}")
print("Similar junctions:")
for junction, distance in result['similar_junctions']:
    print(f"  - {junction} (distance: {distance:.2f})")

# 7. Urban Planning Recommendations Based on Classification
def generate_recommendations(junction_type, similar_junctions, junction_profiles):
    """
    Generate urban planning recommendations based on junction type and similar junctions

    Args:
        junction_type (str): Type of junction
        similar_junctions (list): List of similar junctions with distances
        junction_profiles (DataFrame): DataFrame with junction profiles

    Returns:
        list: Recommended urban planning strategies
    """
    recommendations = []

    # Base recommendations on junction type
    if "High-volume Urban" in junction_type:
        recommendations.extend([
            "Implement advanced traffic light synchronization to optimize flow",
            "Consider dedicated bus lanes to improve public transport efficiency",
            "Install pedestrian countdown timers at crosswalks"
        ])
    elif "High Pedestrian" in junction_type:
        recommendations.extend([
            "Widen sidewalks to accommodate higher pedestrian volume",
            "Add bicycle lanes with physical separation from traffic",
            "Implement pedestrian-priority signaling"
        ])
    elif "Residential" in junction_type:
        recommendations.extend([
            "Install speed bumps or raised crosswalks to reduce vehicle speed",
            "Implement neighborhood traffic calming measures",
            "Consider converting to mini-roundabouts where appropriate"
        ])

    # Add recommendations based on similar junctions
    if similar_junctions:
        most_similar, _ = similar_junctions[0]
        similar_profile = junction_profiles[junction_profiles['junction_id'] == most_similar].iloc[0]

        recommendations.append(f"Review successful strategies implemented at {most_similar}, " +
                              f"which has similar traffic patterns")

        # Add specific recommendations based on similar junction characteristics
        if similar_profile['morning_to_night_ratio'] > 1.5:
            recommendations.append("Consider time-variable traffic management strategies to handle morning peaks")

        if similar_profile['person_to_vehicle_ratio'] > 1.0:
            recommendations.append("Prioritize pedestrian infrastructure improvements")

    return recommendations

# Generate recommendations for the new junction
recom = generate_recommendations(result['junction_type'], result['similar_junctions'], junction_profiles)
print("\nUrban Planning Recommendations:")
for i, rec in enumerate(recom, 1):
    print(f"{i}. {rec}")



# After you've run your clustering analysis and created your models
import joblib

# Save the classifier (Random Forest model)
joblib.dump(clf, "junction_classifier.joblib")

# Save the scaler
joblib.dump(scaler, "feature_scaler.joblib")

# Verify they were saved
print("Models saved successfully.")

"""# Cluster Validation

"""

dublin1_cluster = junction_profiles.loc[
    junction_profiles['junction_id'] == 'Dublin1', 'cluster'
].values[0]
print(f"Dublin1 is in cluster: {dublin1_cluster}")

# Get the feature vector for Dublin 1
dublin1_features = junction_profiles.loc[
    junction_profiles['junction_id'] == 'Dublin1', features.columns
].iloc[0]

# Get the cluster mean
cluster_mean = cluster_profiles.loc[dublin1_cluster]

# Compare
comparison = pd.DataFrame({
    'Dublin1': dublin1_features,
    f'Cluster {dublin1_cluster} Mean': cluster_mean
})
print(comparison)

comparison.plot(kind='bar', figsize=(10, 6), title='Dublin1 vs Cluster Mean')
plt.ylabel("Feature Value")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

junction_profiles[junction_profiles['cluster'] == 0]

"""# Testing

"""

!pip install ultralytics opencv-python pandas numpy joblib yt-dlp scikit-learn

model_path = "junction_classifier.joblib"  # Path to your classifier
scaler_path = "feature_scaler.joblib"      # Path to your scaler

import cv2
import pandas as pd
import time
import numpy as np
import os
from datetime import datetime
from ultralytics import YOLO
import yt_dlp
import joblib
import pickle
from sklearn.preprocessing import StandardScaler

# Define the new junction to analyze
new_junction = {
    "url": "https://www.youtube.com/watch?v=Ku62ggXQPHE",
    "city": "PhilippinesTestCity",
    "junction_id": "new_junction"
}

# Create folders for data and images
today = datetime.now().strftime("%Y%m%d")
data_folder = f"traffic_data/{today}"
images_folder = f"traffic_images/{today}"
os.makedirs(data_folder, exist_ok=True)
os.makedirs(images_folder, exist_ok=True)

# Load your pre-trained models
# Replace these paths with wherever you saved your models
model_path = "junction_classifier.joblib"  # Random Forest model
scaler_path = "feature_scaler.joblib"      # StandardScaler
cluster_names = {
    0: "High-volume Urban Junction",
    1: "Mixed-use with High Pedestrian Activity",
    2: "Low-density Residential Junction"
    # Adjust based on your actual clusters
}

# Load the models
classifier = joblib.load(model_path)
scaler = joblib.load(scaler_path)

def process_new_junction(junction):
    """Process a new junction and save data to CSV"""
    try:
        print(f"Starting analysis of {junction['city']} - {junction['junction_id']}")

        # Create junction-specific images folder
        junction_img_folder = os.path.join(images_folder, f"{junction['city']}_{junction['junction_id']}")
        os.makedirs(junction_img_folder, exist_ok=True)

        # Get direct video URL
        ydl_opts = {'format': 'best[ext=mp4]', 'quiet': True}
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(junction['url'], download=False)
            video_url = info['url']

        # Initialize YOLO
        model = YOLO('yolov8n.pt')

        # Open video stream
        cap = cv2.VideoCapture(video_url)
        if not cap.isOpened():
            print(f"Error: Could not open video stream for {junction['city']} - {junction['junction_id']}")
            return None

        # Prepare data collection
        traffic_data = []
        start_time = time.time()
        frame_count = 0

        # Process for 10 minutes
        processing_time = 600  # 600 seconds = 10 minutes

        print(f"Processing junction for {processing_time/60} minutes...")

        while cap.isOpened() and (time.time() - start_time < processing_time):
            ret, frame = cap.read()
            if not ret:
                break

            # Process every 30th frame
            if frame_count % 30 == 0:
                # Run YOLO detection
                results = model(frame)

                # Count objects
                counts = {'person': 0, 'bicycle': 0, 'car': 0, 'motorcycle': 0, 'bus': 0, 'truck': 0}

                for r in results:
                    for box in r.boxes:
                        class_id = int(box.cls[0].item())
                        confidence = box.conf[0].item()

                        # Map class_id to name
                        if class_id == 0 and confidence > 0.5:
                            counts['person'] += 1
                        elif class_id == 1 and confidence > 0.5:
                            counts['bicycle'] += 1
                        elif class_id == 2 and confidence > 0.5:
                            counts['car'] += 1
                        elif class_id == 3 and confidence > 0.5:
                            counts['motorcycle'] += 1
                        elif class_id == 5 and confidence > 0.5:
                            counts['bus'] += 1
                        elif class_id == 7 and confidence > 0.5:
                            counts['truck'] += 1

                # Store data
                current_time = time.time() - start_time
                data_point = {
                    "timestamp": current_time,
                    "frame": frame_count,
                    **counts
                }
                traffic_data.append(data_point)

                # Print status update
                vehicles = counts['car'] + counts['bus'] + counts['truck'] + counts['motorcycle']
                print(f"{junction['city']} - {junction['junction_id']} | Time: {current_time:.1f}s | Vehicles: {vehicles} | People: {counts['person']}")

            frame_count += 1

        # Release resources
        cap.release()

        # Process the data
        if traffic_data:
            df = pd.DataFrame(traffic_data)

            # Add vehicles column
            df['vehicles'] = df['car'] + df['bus'] + df['truck'] + df['motorcycle']

            # Create filename and save
            filename = os.path.join(data_folder, f"{junction['city']}_{junction['junction_id']}.csv")
            df.to_csv(filename, index=False)
            print(f"Saved raw data to {filename}")

            return df
        else:
            print("No data collected!")
            return None

    except Exception as e:
        print(f"Error processing {junction['city']} - {junction['junction_id']}: {str(e)}")
        return None

def extract_features(df):
    """Extract features from junction traffic data"""
    features = {}

    # Basic traffic volumes
    features['avg_vehicles'] = df['vehicles'].mean()

    # Transport mode distribution
    total_vehicles = df['vehicles'].sum()
    if total_vehicles > 0:
        features['car_percentage'] = (df['car'].sum() / total_vehicles) * 100
        features['bicycle_percentage'] = (df['bicycle'].sum() / total_vehicles) * 100
    else:
        features['car_percentage'] = 0
        features['bicycle_percentage'] = 0

    # Person to vehicle ratio
    features['person_to_vehicle_ratio'] = df['person'].sum() / (total_vehicles + 0.1)

    # Time patterns
    # Since we only have a short sample, we'll use dummy values here
    # In a real implementation, you'd need morning/night and weekday/weekend data
    features['morning_to_night_ratio'] = 1.0  # Placeholder
    features['weekday_to_weekend_ratio'] = 1.0  # Placeholder

    return features

def classify_junction(features):
    """Classify a junction based on its features"""
    # Convert to proper format
    feature_vector = np.array([[
        features['avg_vehicles'],
        features['car_percentage'],
        features['bicycle_percentage'],
        features['person_to_vehicle_ratio'],
        features['morning_to_night_ratio'],
        features['weekday_to_weekend_ratio']
    ]])

    # Scale the features
    scaled_features = scaler.transform(feature_vector)

    # Predict cluster
    cluster = classifier.predict(scaled_features)[0]

    # Get probabilities
    probabilities = classifier.predict_proba(scaled_features)[0]

    # Get cluster name
    junction_type = cluster_names.get(cluster, f"Cluster {cluster}")

    return {
        'cluster': int(cluster),
        'junction_type': junction_type,
        'confidence': float(probabilities[cluster]),
        'feature_values': features
    }

def generate_recommendations(result):
    """Generate urban planning recommendations based on junction type"""
    recommendations = []

    # Base recommendations on junction type
    if "High-volume Urban" in result['junction_type']:
        recommendations.extend([
            "Implement advanced traffic light synchronization to optimize flow",
            "Consider dedicated bus lanes to improve public transport efficiency",
            "Install pedestrian countdown timers at crosswalks"
        ])
    elif "High Pedestrian" in result['junction_type']:
        recommendations.extend([
            "Widen sidewalks to accommodate higher pedestrian volume",
            "Add bicycle lanes with physical separation from traffic",
            "Implement pedestrian-priority signaling"
        ])
    elif "Residential" in result['junction_type']:
        recommendations.extend([
            "Install speed bumps or raised crosswalks to reduce vehicle speed",
            "Implement neighborhood traffic calming measures",
            "Consider converting to mini-roundabouts where appropriate"
        ])

    # Add specific recommendations based on feature values
    if result['feature_values']['person_to_vehicle_ratio'] > 1.0:
        recommendations.append("Prioritize pedestrian infrastructure improvements")

    if result['feature_values']['bicycle_percentage'] > 15:
        recommendations.append("Add dedicated bicycle lanes and bicycle-specific signaling")

    if result['feature_values']['avg_vehicles'] > 50:
        recommendations.append("Consider expanding road capacity or implementing advanced traffic management")

    return recommendations

# Main execution flow
print(f"Starting analysis of new junction: {new_junction['city']} - {new_junction['junction_id']}")
print("Collecting traffic data for 10 minutes...")

# Process the junction
junction_data = process_new_junction(new_junction)

if junction_data is not None:
    print("\nData collection complete. Extracting features...")

    # Extract features
    features = extract_features(junction_data)
    print("\nExtracted Features:")
    for key, value in features.items():
        print(f"  {key}: {value:.2f}")

    # Classify the junction
    print("\nClassifying junction...")
    result = classify_junction(features)

    print("\n=== JUNCTION CLASSIFICATION RESULTS ===")
    print(f"Junction Type: {result['junction_type']}")
    print(f"Confidence: {result['confidence']:.2f}")

    # Generate recommendations
    recommendations = generate_recommendations(result)

    print("\n=== URBAN PLANNING RECOMMENDATIONS ===")
    for i, rec in enumerate(recommendations, 1):
        print(f"{i}. {rec}")

    print("\nAnalysis complete!")
else:
    print("Analysis failed - no data was collected.")